### ISSUE TITLE
Ambassador-agent permissions are too broad

### ISSUE THREAD

**Issue by knlambert** [datawire/ambassador-agent#98]
We got this email from an external user : 

```
Dear telepresence maintainers:
I am Nanzi Yang, and I find a potential risk in telepresence which can
be leveraged to get the cluster's admin token.

Detailed analysis:
The telepresence has one deployment called
traffic-manager-ambassador-agent, which runs on a worker node randomly
and has a service account traffic-manager-ambassador-agent. The
service account has a cluster role called
traffic-manager-ambassador-agent, which has "get list" verbs of
"secret" resources. Thus, if a malicious user can access the worker
node which has this deployment, or he/she can access this pod
directly, he/she can leverage the pod's service account to get ALL
secrets in the entire cluster, resulting in cluster-level privilege
escalation.

Mitigation discussion:
1. The maintainer can use the RoleBinding, NOT the ClusterRoleBinding,
to restrain the service account and can only access the secret inside
the ambassador namespace.
2. The maintainer can use the secret name to restrain the secrets can
be accessed by this deployment.

A few questions:
1. Is it a real issue in telepresence?
2. If it's a real issue, can telepresence fix it following my suggestions?
Looking forward to your reply.
Regards,
Nanzi Yang
```

We don't think this is exactly a vulnerability, but it points out that the permission is indeed a[ little too large.](https://github.com/datawire/ambassador-agent/blob/master/helm/ambassador-agent/templates/clusterrole.yaml#L65)

* First we need to understand if that permission is still required. Use cases we can think about:
    * API Key creation from the cloud app. 
    * Reading the credentials to connect to the cloud.
* Depending on how large is the scope, here are some solutions:
    * Put that in a namespace scoped role since we don't do anything outside of the installation namespace.
    * We probably know the name given to these secrets, so only use a get instead of a list (Although the api key feature may make these solution impossible).
    * Don't do anything if the permission is actually important.

**Comment by younaman** [comment]
Hello, I am Nanzi Yang, the reporter of this issue.
